### ISSUE TITLE
I get a null object reference while trying to use FixedHeaderTableLayout with retrofit

### ISSUE THREAD

**Issue by wissedenis** [Zardozz/FixedHeaderTableLayout#1]
Am trying to create fixed header table layout using FixedHeaderTableLayout. I have some users which I retrieve from the server using retrofit. Below is the code. However If I run the app in debug mode and set the breaking points on `for (int i = 1; i <=userNames.size(); i++) { ` it runs perfect! I guess the problem is with retrofit not returning the results faster.

```
int daysInMonth = 29
    private List<AttendanceModel> userNames = new ArrayList<>();

    protected void onCreate(Bundle savedInstanceState) {
        ............................
    ........................................
    ....................................
    //request to get the number of Users from the server using retrofit
        ApiInterface api = ApiClient.getRetrofit().create(ApiInterface.class);
        Call<ListUsers> products = api.get_attendance();
        products.enqueue(new Callback<ListUsers>() {
            @Override
            public void onResponse(Call<ListUsers> call, Response<ListUsers> response) {
                if(response.body()!=null){
                    userNames = response.body().getNames();

                  ..............................
    ............................................
    });

        // Really this should be done in the background as generating such a big layout takes time
        GenerateTables generateTables = new GenerateTables(this);
        generateTables.execute();


    }

@SuppressLint("SetTextI18n")
    private void createTable(Context mContext){
        // Create our 4 Sub Tables
        mainTable = new FixedHeaderSubTableLayout(mContext);  
        // 25 x 5 in size
        float textSize = 20.0f;
        for (int i = 1; i <=userNames.size(); i++) { // userNames = 7
            FixedHeaderTableRow tableRowData = new FixedHeaderTableRow(mContext);
            // Add some data
            for (int j = 1; j <= daysInMonth; j++) { // daysInMonth = 29
                // Add a Textview
                TextView textView = new TextView(mContext);
                textView.setGravity(Gravity.CENTER);
                textView.setText(String.format(Locale.ROOT,"C%d:R%d", j, i)); 

                textView.setBackgroundResource(R.drawable.list_border);
                textView.setPadding(5 ,5,5,5);
                textView.setTextSize(textSize * 1.5f);
                textView.setTextColor(getResources().getColor(R.color.colorText));
                tableRowData.addView(textView);
            }
            mainTable.addView(tableRowData);
        }
.........
..............................
...............................

```

Whenever I run the code I get error as follow;

> E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1 Process: com.example.distance, PID: 7096 java.lang.RuntimeException: An error occurred while executing doInBackground() at android.os.AsyncTask$4.done(AsyncTask.java:415) at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) at java.util.concurrent.FutureTask.setException(FutureTask.java:252) at java.util.concurrent.FutureTask.run(FutureTask.java:271) at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:923)
> 
> Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference at com.github.zardozz.fixedheadertablelayoutsample.MainActivity.createTable(MainActivity.java:192) at com.github.zardozz.fixedheadertablelayoutsample.MainActivity.access$200(MainActivity.java:59) at com.github.zardozz.fixedheadertablelayoutsample.MainActivity$GenerateTables.doInBackground(MainActivity.java:153) at com.github.zardozz.fixedheadertablelayoutsample.MainActivity$GenerateTables.doInBackground(MainActivity.java:128) at android.os.AsyncTask$3.call(AsyncTask.java:394) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)  at java.lang.Thread.run(Thread.java:923)

**Comment by Zardozz** [comment]
This is a threading timing issue with your Call to `Retrofit`.

Because the call to Retrofit to get the data is Asynchronous it does not stop the execution on the `onCreate` method thus the code goes on to try and create the table before you have any data back to create the table with.

The following re-ordering of the code in the `onCreate` method should work.

```
protected void onCreate(Bundle savedInstanceState) {
        ............................
    ........................................
    ....................................
    
    // Really this should be done in the background as generating such a big layout takes time
        GenerateTables generateTables = new GenerateTables(this);
    
    //request to get the number of Users from the server using retrofit
        ApiInterface api = ApiClient.getRetrofit().create(ApiInterface.class);
        Call<ListUsers> products = api.get_attendance();
        products.enqueue(new Callback<ListUsers>() {
            @Override
            public void onResponse(Call<ListUsers> call, Response<ListUsers> response) {
                if(response.body()!=null){
                    userNames = response.body().getNames();
                    
                    // Only try to generate the table when Retrofit has returned the usernames needed.
                    generateTables.execute();

                  ..............................
    ............................................
    });

      }
```
