### ISSUE TITLE
The table is not scrolled up when inside SwipeRefreshLayout

### ISSUE THREAD

**Issue by yaugenka** [Zardozz/FixedHeaderTableLayout#3]
When the widget is inside a SwipeRefreshLayout and you pull the screen down, it won't scroll, but trigger the swipe refresh instead.
You have to first pull the screen up and then down to make it scroll.

**Comment by Zardozz** [comment]
At the moment the Table is really only designed to be used as a single layout on screen and handle all scroll movements.
It has a bit of a complicated Motion detection and it is getting more complicated to allow clicks.
I'll need to look in to more as to why this is happening.

**Comment by yaugenka** [comment]
The issue was caused by the table placed inside a LinearLayout within the SwipeRefreshLayout. If placed directly withing the SwipeRefreshLayout, it works correctly.
