### ISSUE TITLE
Scrollbars don't reappear when fadeScrollbars=true

### ISSUE THREAD

**Issue by yaugenka** [Zardozz/FixedHeaderTableLayout#4]
With `fadeScrollbars` enabled, the scrollbars appear only once at first load, then fade out and never appear again.

**Comment by Zardozz** [comment]
At the moment I only Override the calculations of the scrollbar sizes and leave the rest to the FrameLayout Code, but may be it is something to do with the Motion Events processing, so I will need to investigate this more.

**Comment by Zardozz** [comment]
Fixed by commit https://github.com/Zardozz/FixedHeaderTableLayout/commit/4e2cf4f6a2d0b9d4438e94358bf33f8f08461324

Will release version 0.0.0.3 soon with it in.
