### ISSUE TITLE
Scroll to botom

### ISSUE THREAD

**Issue by tonydsouza1987** [Zardozz/FixedHeaderTableLayout#7]
Hi Gents,
Thank you for the great table which is very useful.
I implemented this table as I needed the fixed headers (row, column, and corner).
Since I have almost 800 rows in main table (or row header table), i want to scroll to end/bottom after the table is populated.
I tried several ways of doing it by setting the scrollTo(0,maintable.getBottom) and aso tried doing it in post runnable.

Could you please provide a working solution for me.

Edit: I just want the main table (with row header table) to scroll vertically to bottom.

Thanks,
Tony

**Comment by Zardozz** [comment]
This is something that probably needs adding as functionality.

The inherited `scrollTo` won't work because the `FixedHeaderTableLayout` view is not actually scrollable itself, it moves (and scales) it's 4 child views.

This is something I'll look at when I get time.

But as a quick hack you could directly call `calculatePanScale(float distanceX, float distanceY, float centerX, float centerY, float newScaleFactor)` as this is public and is actually what moves the views with a very large `distanceY` as the code won't allow you to scroll past the bottom.

e.g. something like might work (not tested)

`myFixedHeaderTableLayout.calculatePanScale(0f,Float.MAX_VALUE,0f,0f,1f)`

**Comment by tonydsouza1987** [comment]
Hi Zardozz,
Thank you for your prompt response. Really appreciate your response.
As you said, to call the method calculatePanScale() method as below, did the trick. Yes the table scrolls to bottom. But the row table header and main table header is not visible untill i touch and swipe up/down/scroll. Only corner table and column header table are visible after calling that method.
`fixedHeaderTableLayout.calculatePanScale(0f,Float.MAX_VALUE,0f,0f,1f);`

I tried to pass motion events dispatch for every table as below. Which still did not worked.

` MotionEvent e = MotionEvent.obtain( SystemClock.uptimeMillis(),
                    SystemClock.uptimeMillis()+200,
                    MotionEvent.ACTION_DOWN,
                    0.0f, 0.0f, 0);
            mainTable.dispatchTouchEvent(e);`

Also i tried calling requestFocus() on all tables, which did not worked too.
Lastly i treid to call method bringToFront() which is same, need to swipe, plus it overlaps on other table. Tried setVisibility() with no luck.
```
mainTable.setVisibility(View.VISIBLE);
rowHeaderTable.setVisibility(View.VISIBLE);
```

So, do you have any quick fix to make them visible after calling calculatePanScale()???

Thank you for your support.

Tony

**Comment by Zardozz** [comment]
The question is when do you call calculatePanScale?

I tried this in the sample App and everything worked as expected.

I added the following after the line https://github.com/Zardozz/FixedHeaderTableLayout/blob/master/app/src/main/java/com/github/zardozz/fixedheadertablelayoutsample/MainExampleActivity.java#L125

`fixedHeaderTableLayout.calculatePanScale(0f,Float.MAX_VALUE,0f,0f,1f);`

And it correctly scrolled to the bottom of the table and showed everything correctly.

This is a screen shot of the sample app with that change.

![Screenshot_1664891911](https://user-images.githubusercontent.com/13763054/193840404-95c5df12-76d3-4870-8d61-c9cc1b3fa02a.png)

I think possibly you calling it too early before everything is drawn fully?

`calculatePanScale()` is method called from scroll and scale touch events.

Without seeing your code or a fully working example of where it does not work then it is a bit difficult to help.

**Comment by tonydsouza1987** [comment]
Hi Zardozz,
Thank you again.
I was calling `calculatePanScale()` method after the adding child tables( in Async postExec) as below:

`fixedHeaderTableLayout.addViews(mainTable, columnHeaderTable, rowHeaderTable, cornerTable); pBar.setVisibility(View.GONE);
fixedHeaderTableLayout.setVisibility(View.VISIBLE);
fixedHeaderTableLayout.calculatePanScale(0f,Float.MAX_VALUE,0f,0f,1f);`

Yes, its a huge list and so did not worked since the drawing was not completed, and my call ran in before.

It works now, after i changed it to below (calling calculatePanScale()  inside onLayoutChangeListener()) method:
`fixedHeaderTableLayout.addViews(mainTable, columnHeaderTable, rowHeaderTable, cornerTable);
            pBar.setVisibility(View.GONE);
            fixedHeaderTableLayout.setVisibility(View.VISIBLE);
            fixedHeaderTableLayout.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
                @Override
                public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
                    fixedHeaderTableLayout.calculatePanScale(0f,Float.MAX_VALUE,0f,0f,1f);
                }
            });`

Also worked in post runnable :
` fixedHeaderTableLayout.postDelayed(new Runnable() {
                @Override
                public void run() {
                    fixedHeaderTableLayout.calculatePanScale(0f,Float.MAX_VALUE,0f,0f,1f);
                }
            }, 1000);`

Hope this is the  right way, I am not sure. If there is a better way let me know. I am keeping the call inside onLayoutChange.

Thanks,
Tony
