### ISSUE TITLE
Not able to disable zoom on the table

### ISSUE THREAD

**Issue by muaviyaijaz123** [Zardozz/FixedHeaderTableLayout#8]
**Describe the bug**
this library fits our project need for table with both horizontal and vertical scrolling. However, I am not able to disable zoom for the table so that it remains in a standard size like any recycler view on any android device. Is there a way to do this?

**Expected behavior**
Table should be not be able to zoom in or zoom out

**Tools:**
 - `FixedHeaderTableLayout` version:  0.0.0.5
 - Android version: 11

**Comment by Zardozz** [comment]
Have you tried setting `MinScale` and `MaxScale` to `1.0f` ?

That should not allow the zoom scale to change and thus disable zoom.

**Comment by muaviyaijaz123** [comment]
Yes, this worked for me. Thanks!
